name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY_URL: https://hub.docker.com/repository/docker/youngmukde/stream_daq
  REPOSITORY_NAME: youngmukde/stream_daq

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_URL }}/${{ env.REPOSITORY_NAME }}:latest

